name: Tests

on:
  push:
    branches: [  ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [  ]

  workflow_dispatch:
  


jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${GITHUB_REF#refs/heads/}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true

  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v2.0.0
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: 
      - Linting
      - Formatting
    steps:
    - uses: actions/checkout@v4

    # - name: Test workflow
    #   uses: snakemake/snakemake-github-action@v2.0.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "--use-conda --show-failed-logs --cores 1 --conda-cleanup-pkgs cache --all-temp --configfile .test/config.yaml"
    #     stagein: "conda config --set channel_priority strict"

    # - name: Test report
    #   uses: snakemake/snakemake-github-action@v2.0.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "--report report.zip"
