name: MyWorkflow Tests

on:
  push:
    branches: [ main ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test workflow
    runs-on: ubuntu-latest
    steps:
    - name: run planemo test
      run: sleep $(( $RANDOM % 50 + 1 )) && echo "ok"
